### PR TITLE
Add member text fix

### PR DESCRIPTION
**Pull request by simonisfiction**
user  input is now checked when the member submit button is pressed.  code is at around line 650 of mainwindow.cpp

### CODE REVIEW

**Comment by bigverl** [comment]
"Name" field allows unlimited characters and accepts numbers and non-letter characters. Suggest only allowing letters and limiting the character count to 50 as per the database schema's character limit.

**Comment by bigverl** [comment]
Allows user to enter name of existing user once, but not twice.
Doesn't capitalize the first letter of names following the first.
e.g. "First last" rather than "First Last"

**Comment by Dogguy0210** [comment]
Tested and approve tab order, though would like to see pressing enter and a selected button responding the same as clicking the button. I suggest this to be part of the hotkey branch so that this branch may be merge

**Comment by simonisfiction** [comment]
things to test:
id only allows numbers typed in
warning message comes up if id isn't present
warning message comes up if name isn't present
first letters of first middle and last names are capitalized
maximum character count in id  should be 6
maximum character count in name should be 50

**Comment by noahvaks** [comment]
id field allows a '+' sign as the first character

**Pull request merged**
